name: Continuous

on: [push]

jobs:

  linux-mac:
    strategy:
      matrix:
        cfg: [{os: ubuntu-latest, cxx: g++},
              # {os: ubuntu-latest, cxx: g++-9},
              # get clang 16 ! because we need C++20 support
              {os: macos-latest, cxx: /opt/homebrew/opt/llvm@16/bin/clang++}] 
        config: [Release, Debug]

    runs-on:  ${{ matrix.cfg.os }}

    env:
      CXX: ${{ matrix.cfg.cxx }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Clang 16 (macOS)
      if: matrix.cfg.os == 'macos-latest'
      run: |
        brew install llvm@16

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DUM_UNIT_TESTS=ON

    - name: CMake Build
      run: cmake --build build --parallel

    - name: CTest
      run: ctest --test-dir build -V

  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -DUM_UNIT_TESTS=ON

    - name: Release build
      run: cmake --build build --parallel --config Release

    - name: Release CTest
      run: ctest --test-dir build -C Release -V

    - name: Debug build
      run: cmake --build build --parallel --config Debug

    - name: Debug CTest
      run: ctest --test-dir build -C Debug -V
